FROM quay.io/rocker/rstudio:rhel7-3.6.0

RUN yum -y install \
  libxml2-devel \
  cairo-devel \
  sqlite-devel \
  mariadb-devel \
  libpqxx-devel \
  libssh-devel \
  unixodbc-dev \
  && yum clean all \
  && rm -rf /var/cache/yum \
  && Rscript --verbose -e 'install.packages(c("tidyverse", "dplyr", "devtools", "formatR", "remotes", "selectr", "caTools", "BiocManager"), repos="http://cran.r-project.org")'

