FROM quay.io/rocker/rstudio:rhel7-3.5.2

RUN yum -y install \
  libxml2-devel \
## wanted cairo2 but don't see that in RHEL...
  cairo-devel \
  sqlite-devel \
  mariadb-devel \
##  libmariadb-client-lgpl-dev \
  libpqxx-devel \
  libssh-devel \
  unixODBC-devel \
  && yum clean all \
  && rm -rf /var/cache/yum \
  && Rscript --verbose -e 'install.packages(c("tidyverse", "dplyr", "devtools", "formatR", "remotes", "selectr", "caTools", "BiocManager"))'

